# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-AccountAutoDiscovery
version:      0.06
version_from: lib/HTML/AccountAutoDiscovery.pm
installdirs:  site
requires:
    Class::ErrorHandler:           0
    LWP::UserAgent:                0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
